### ISSUE TITLE
Edge weight integer

### ISSUE THREAD

**Issue by Roconda** [bitwalker/libgraph#14]
Hi,

I want to do path finding between multiple vertexes. I'm adding edges but my current weight values are decimal. The library returns the  following message:

>  (ArgumentError) invalid value for :weight, must be an integer

I understand that integers are faster and don't have rounding errors. What is the reason that weights must be an integer?

ps: thanks for the lib :-)

**Comment by georgewhewell** [comment]
I made the following modifications and it seems to work: https://github.com/georgewhewell/libgraph/commit/548f3142511af36d2214df847bbc4c6624e59a7c

ymmv

**Comment by bitwalker** [comment]
Addressed in #19
