### ISSUE TITLE
DOT output should quote edge label text

### ISSUE THREAD

**Issue by yonkeltron** [bitwalker/libgraph#2]
The DOT serialization feature is really handy! I can see myself adding TGF support in the future (in my copious free time) so there could be other serialization formats coming along.

In the meantime, the label text for edges should be quoted. I have a forward slash in my labels and noticed that it causes `dot` to spit out an error.

```
...syntax error in line 10 near '/'
```

The label looks like `[label=HTTP/80; weight=1]` but should look something like `[label="HTTP/80"; weight=1]`.

Can I provide additional information or something?

**Comment by bitwalker** [comment]
Nice catch! You are absolutely correct, I'll get that patched up :)

**Comment by bitwalker** [comment]
Fixed in 46fbc7a, and released in 0.10.2. Thanks!
