### ISSUE TITLE
[Contributing] Fresh clones don't work out of the box.

### ISSUE THREAD

**Issue by wanderanimrod** [bitwalker/libgraph#8]
Hello @bitwalker, thanks for your work on this lib.

I just cloned this repo, run `mix deps.get` and `mix test` and got the following error.

```
$ mix test
** (CompileError) test/model_test.exs:3: module :eqc_gen is not loaded and could not be found
    (eqc_ex) expanding macro: EQC.__using__/1
    test/model_test.exs:3: Graph.Model.Test (module)
    (elixir) expanding macro: Kernel.use/1
    test/model_test.exs:3: Graph.Model.Test (module)
    (eqc_ex) expanding macro: EQC.ExUnit.__using__/1
    test/model_test.exs:3: Graph.Model.Test (module)
    (elixir) expanding macro: Kernel.use/1
    test/model_test.exs:3: Graph.Model.Test (module)
    (elixir) lib/code.ex:370: Code.require_file/2
    (elixir) lib/kernel/parallel_require.ex:57: anonymous fn/2 in Kernel.ParallelRequire.spawn_requires/5
```
Is there anything more than `mix deps.get` that needs to be done in order to get up and running?

Thanks.

**Comment by wanderanimrod** [comment]
I have run `mix eqc.install --mini` and was able to run tests. I looked at [the travis config](https://github.com/bitwalker/libgraph/blob/master/.travis.yml#L12) to figure it out.

Should this be in a contributor's guide somewhere?

**Comment by bitwalker** [comment]
It should, sorry about that, I'll get that updated accordingly :)
