### ISSUE TITLE
Neo4j Serializer

### ISSUE THREAD

**Issue by wanderanimrod** [bitwalker/libgraph#9]
Hello @bitwalker ,

I am working on exporting my `libgraph` graph to Neo4j. I see the way you do that for GraphViz is by using the [in-built DOT serializer](https://hexdocs.pm/libgraph/Graph.Serializers.DOT.html#serialize/1).

Where should new serializers live? Should they be contributed back to `libgraph` or should they simply implement the  [`Graph.Serializer`](https://hexdocs.pm/libgraph/Graph.Serializer.html#c:serialize/1) behaviour and live in their own libraries?

Thanks.

**Comment by bitwalker** [comment]
I think ideally they should live in their own libraries, but I'm willing to consider the inclusion of some extensions assuming I can maintain them and they are widely applicable. In this specific case I would provide this as it's own library, as I won't be able to maintain it myself.
